### ISSUE TITLE
Pressure inverse property routines for igmix

### ISSUE THREAD

**Issue by themrdjj** [chmarti1/PYroMat#11]
Why doesn't the `igmix` class have the inverse methods `p_s` and `p_d` (which `ig` does have)?  Wouldn't this work in the same way as `_invT`, or am I missing some details from thermodynamics?

**Comment by chmarti1** [comment]
Good question!  I'm actually working to re-design the ideal gas interface right now, and that's one of the shortcomings I'm planning to fix.

In the meantime, there's good news... you don't actually need special iterative routines to evaluate those quantities anyway.  Yes, ideal gas theory gives us straightforward formulae.

To calculate pressure from density, you can simply use the ideal gas law.  Just calculate R or mean molecular weight for the mixture and use that to calculate p.

p = d * R * T
  OR
p * mw = d * Ru * T

where mw is the molecular weight and Ru is the molar (universal) ideal gas constant.

To calculate pressure from entropy, you can just use the ideal gas law for entropy:

s(T,p) = s(T,p0) - R ln(p / p0)

s(T,p0) is entropy as a function of temperature at a reference pressure.
p0 is the reference pressure.
R is the ideal gas constant.
If you know s(T,p) and you know T, you can solve for p.

I am working on an alpha release now that will standardize the ideal gas interface so there is better inverse support across all of the different classes.

Regards,


Christopher R. Martin Ph.D.

Assistant Professor of Mechanical Engineering

Penn State University - Altoona College

(+1 814) 949-5227

https://sites.psu.edu/cmartin


________________________________

**Comment by themrdjj** [comment]
Thanks for clearing that up, it seems like I got confused about my thermodynamics for a second. In the meantime I have implemented it myself in a very simple way using `scipy.optimize`:

```
def p_s(s, t):
    def func(p):
        return air.s(t, p) - s
    return optimize.newton(func, 1.)
```

So why did you implement the inverse temperature methods iterationally? Is it because of the temperature dependence of c<sub>p</sub>?

**Comment by chmarti1** [comment]
Yes.  Only perfect gases can use explicit inversion.  The heat capacity is a complicated polynomial on temperature, and some models use non-polynomial terms as well.  That established, there isn't a good explicit method to invert properties on temperature.

If you look at monoatomic species like argon, they behave much more like a perfect gas (constant cp).  Why?

For a species that acts like a simple sphere, its only effective means for storing energy is by translation (flying around through space).  Molecules with more complicated shapes have more complicated mechanisms for storing internal energy (they can vibrate and spin as well as fly around in a straight line).  As temperature is increased, these more complicated modes "kick-in" and start increasing the apparent specific heat.

http://hyperphysics.phy-astr.gsu.edu/hbase/thermo/inteng.html#c4

For electrically conductive solids, there's a whole other conversation

http://hyperphysics.phy-astr.gsu.edu/hbase/thermo/Dulong.html#c1

________________________________
