### ISSUE TITLE
Custom gas mixture

### ISSUE THREAD

**Issue by KBMSeb** [chmarti1/PYroMat#13]
Hello, 
Is it possible to create custom gas mixture from existing 'ig' given the molar or mass ratio of the diffrent species ?
Or is the igmix restricted to the predefined mixtures from the aatabase?

thank you in advance, 
Mahmoud

**Comment by chmarti1** [comment]
Thank you for your interest in PYroMat!

There are two ways to go about calculating properties of custom gas mixtures with PYroMat:

  1.  Create your own instance of the igmix class.
  2.  Calculate the properties on your own from the constituents.

Which one and how you go about it depends on what you're trying to do.  Creating your own igmix instance works well if you have a static mixture (like air) that doesn't change.  Calculating your own properties makes sense if you have a mixture that can vary (like in a chemical reaction).

There are plans to make this process easier in the future, but they won't make it into version 2.1.0, which is currently under development.

Creating your own persistent igmix instance
If you want the igmix instance to be permanent (if you want it to appear in the collection each time you load PYroMat), you'll need to create an ".hpd" file for it, and you'll need to put that file somewhere PYroMat can find it<http://pyromat.org/doc_api.html#import_dat> when it loads.

HPD files are in the "json" format, and they create a Python dictionary that contains the raw data for each class.  Here are the actual contents of the "air.hpd" file that defines the air mixture:
```JSON
{
    "bymass": false,
    "class": "igmix",
    "contents": {
        "ig.Ar": 0.935,
        "ig.CO2": 0.0314,
        "ig.N2": 78.084,
        "ig.O2": 20.9476
    },
    "doc": "The composition of air is taken from section 14 page 20 of the  the CRC Handbook of Chemistry and Physics 96th ed, 2015-2016.\n\nwww.hbcpnetbase.com\n\nTrace gases (those present in less than 0.01% by volume) are neglected, as they will not contribute substantially to the thermodynamic properties.\n\nOriginal work is credited to:\n\nCOESA, \"U.S. Standard Atmosphere, 1976\", U.S. Government Printer Office, Washington D.C., 1976.\n\nAdapted by Chris Martin (c) 2015.\n",
    "id": "ig.air"
}
```

You'll want to edit the "doc" "id" and "contents" values (and possibly the "bymass" value).  The mixture can be specified by mole/volume or by mass.  This mixture is specified by mole count, so the "bymass" value is false.  Feel free to change that to true if you need to.

Creating a temporary igmix instance
If this is a one-time thing, and you won't need this mixture the next time you run PYroMat, then you can also do this on the fly.  Here's an example where we steal the data dictionary from the air instance, copy it, edit it, and make a new instance.
```Python
import pyromat as pm
air = pm.get('ig.air')
data = air.data.copy()
# ... edit the data dictionary to suit ...
mymix = pm.reg.registry['igmix'](data)
```
Note that this will create an instance of the igmix class that is NOT registered in the PYroMat database, so other PYroMat instances will not be able to find it.  For the vast majority of all applications, that won't matter.

Calculating your own mixtures
One of the key motivations for making PYroMat Numpy array compatible is so it is easy to calculate properties on big data sets like those generated in combustion modeling.  For the sake of simplicity, though, let's look at a way to do this on one value at a time.  Here, we replicate the calculation of enthalpy for h35 (35% H2 and 65% Ar by vol. is a gas blend popular in the welding/cutting industry for stainless steels).
```Python
Import pyromat as pm
Ar = pm.get('ig.Ar')
H2 = pm.get('ig.H2')
h35 = pm.get('ig.h35')
# Switch to molar units for volumetric ratios
pm.config['unit_matter'] = 'kmol'
h = 0.35 * H2.h(1000) + 0.65 * Ar.h(1000)
# h is 16722.97789141 kJ/kmol
h = h35.h(1000)
# h is still 16722.97789141 kJ/kmol
```

Hope that helps!
-
C.M.

**Comment by KBMSeb** [comment]
Thank you for your quick and helpful reply!
I look forward to the next upgrades. Great work!

**Comment by chmarti1** [comment]
This idea has finally made it to the top of the update list.  In version 2.2.5, there is a new `igtools` module, which provides a class called `IgtMix`.  It allows users to much more conveniently create dynamic mixtures from the command line.  It supports mixture arrays, it handles the "entropy of mixing" calculations correctly, and it now provides Gibbs energy.

Thanks for using PYroMat!
