### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by beckerrh** [chmarti1/PYroMat#15]
Hello there,
I am having the following issue 
"""
 s = O2.s(T,p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pyromat/registry/ig2.py", line 821, in s
    out = self._s(T,p)[0] - pm.units.const_Ru * np.log(p/self.data['pref'])
  File "/usr/local/lib/python3.9/site-packages/pyromat/registry/ig2.py", line 645, in _s
    if diff:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
"""
when running the example
"""
import numpy as np
import pyromat as pm
O2 = pm.get('ig.O2')
T = np.linspace(300.,2000.,101)
p = np.linspace(1.,100.,101)
s = O2.s(T, p)
"""
.... it seems to me that the method _s takes as second a argument a boolean and not an array....
Many thanks for any help !

**Comment by chmarti1** [comment]
Thank you for raising the issue.  This is a bug that wasn't caught in testing.  The _s(T,p)[0] should not have the pressure argument.  I should be able to upload a fix before the end of the day.

**Comment by chmarti1** [comment]
I have pushed v2.1.3, which deals with this issue.  It was not revealed in testing, because it only happens when array values are supplied to pressure.  I will update the python package index and sourceforge distributions soon.

**Comment by beckerrh** [comment]
Thanks a lot! I’ve just seen that I didn’t answer, sorry !
Best regards,
Roland

**Comment by chmarti1** [comment]
No worries.  Thanks again for opening the issue.
