### ISSUE TITLE
Bug in cp(), cv(), and gam()

### ISSUE THREAD

**Issue by Matthew-Mullin** [chmarti1/PYroMat#18]
I tried calling air.cp(), air.cv(), and gam(), but found that the "bootstrap" method had a typo:

`AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_16868/1963525599.py in <module>
----> 1 air.cp()

C:\ProgramData\Anaconda3\lib\site-packages\pyromat\registry\igmix.py in cp(self, *varg, **kwarg)
    544 Returns:    Spec. Heat  [unit_energy / unit_temperature / unit_matter]
    545 """
--> 546         self._boostrap()
    547         # Parse the arguments to isolate temperature in K
    548         T = self._argparse(*varg, temperature=True, **kwarg)

AttributeError: 'igmix' object has no attribute '_boostrap'`

**Comment by chmarti1** [comment]
You're right.  There are some other errors in the igmix class that seem to have slipped through testing as well.  I will release a fix before the end of the day.

**Comment by chmarti1** [comment]
That went faster than expected.  I pushed version 2.1.4 with these fixes, and you should be able to upgrade from the package index now.  Thanks for posting the bug!
