### ISSUE TITLE
Literal verbose flag in mp1.py

### ISSUE THREAD

**Issue by jranalli** [chmarti1/PYroMat#24]
It looks like while debugging, you left a verbose flag set to True, because it's outputting unnecessarily:

[mp1.py line 2111](https://github.com/chmarti1/PYroMat/blob/50b6332316175d93bf2688e500ae584762811f85/src/pyromat/registry/mp1.py#L2111)    ```param={'fn':self._p, 'd':d}, verbose=True)```

**Comment by chmarti1** [comment]
Well, there's a rookie mistake.  Stare at verbose output long enough, and it starts to look normal!  Thanks for the flag.  Now patched.
