### ISSUE TITLE
Import error on pyromat.aps.cycle

### ISSUE THREAD

**Issue by jranalli** [chmarti1/PYroMat#25]
Import error on calling
```
import pyromat.aps.cycle
```
It complains about the call from the ```aps.__init__.py ```
https://github.com/chmarti1/PYroMat/blob/7e3d5d249f72c4451a44294c38968a246260eee3/src/pyromat/aps/__init__.py#L1

```
ModuleNotFoundError: No module named 'cycle'
```

I admittedly am horrible at python packaging but I tried every permutation of the cycle import I could and get errors no matter what. I think there's something wrong with the namespace there. On a test copy, I removed the import in ```aps.__init__.py``` and it works, but that may not be the namespace you were trying to create.

**Comment by chmarti1** [comment]
You're right; this is a namespace issue left over from old experiments with the aps module.  I haven't paid the aps module serious attention in quite a while.  I need a good think about how to reorganize things there, but in the meantime, it's a perfectly good work-around to simply delete aps.__init__.py.  The original design intent was that users could optionally import "aps" and all of the modules would appear, but the existing __init__.py obviously doesn't accomplish that.

I'll leave this open as a bug until I implement a more elegant fix.
