### ISSUE TITLE
Default pressure does not obey units

### ISSUE THREAD

**Issue by akiss-ic** [chmarti1/PYroMat#29]
Hi, apologies in advance if this is not the correct place to ask this or if this is a stupid user error rather than an actual bug (I am very new to PyroMat).

I have modified my config.py file to set `unit_pressure = 'Pa'` rather than bar and this works well with one exception. If I run the pressure method with no arguments, e.g. `air.p()` I get the result in bar still rather than Pascals: `array([1.01325])`. Running it with named arguments, however, `air.p(T=300, d=1.225)` returns Pascals as expected: `array([105491.85213083])`. This does not seem to be the case for the default enthalpy when I change the energy units from kJ to J and it reports the enthalpy in J as expected.

Am I missing something obvious?

Thanks!

**Comment by chmarti1** [comment]
As of version 2.2.5, PYroMat no longer handles the default temperature and pressure in this way.  See issue #97 for a more detailed description.  See the [PYroMat User and Developer Handbook Chapter 3](http://pyromat.org/pdf/handbook.pdf#page=41) for information on the configuration system.
