### ISSUE TITLE
Enthalpy of formation for Acetylene

### ISSUE THREAD

**Issue by DerickBO** [chmarti1/PYroMat#31]
Dear Christopher, when calculating the enthalpy of formation for Acetylene (C2H2), it returns a value of 414,785.804. This value is different to the value that is shown in other literatures of 226,730 kJ/kmol. 

`C2H2 = pm.get("ig.C2H2")`
`C2H2.h(T=25+273.15)*C2H2.mw()`

**Comment by chmarti1** [comment]
Thank you so much for your long patience.  Version 2.2.0 has a number of collection improvements.  One of them is a return to the correct data for Acetylene.
