### ISSUE TITLE
Bug in mp1.hsd()

### ISSUE THREAD

**Issue by jranalli** [chmarti1/PYroMat#32]
Observed a crash in mp1.hsd(). Crash occurs because it attempts to combine arrays of different sizes, since parts of the calculation are not properly indexed. 

Minimal code to demonstrate the crash:
```python
import pyromat as pm
h2o = pm.get('mp.H2O')
h2o.hsd(p=[1.611654e-2, 2.8095e-2], d=[999.056])
```

Fix is easy affecting lines 3080 and 3081 of [mp1.py](https://github.com/chmarti1/PYroMat/blob/77377dcda05d476d19ceb19549e927592b180276/src/pyromat/registry/mp1.py#L3080), pull request incoming.

**Comment by chmarti1** [comment]
Confirmed.  I can reproduce the error in my installation.  The error is on lines 3075 and 3076.  T and d should be indexed before being passed to _ar() to prevent calculating over the entire array.
