### ISSUE TITLE
Typo bug in igmix.py

### ISSUE THREAD

**Issue by jranalli** [chmarti1/PYroMat#41]
Call in igmix.py should be [pm.units.temperature_scale()](https://github.com/chmarti1/PYroMat/blob/c4024e114eb9c613be545a818b3710780acc249b/src/pyromat/registry/igmix.py#L649)

**Comment by chmarti1** [comment]
This looks like a second instance of a [similar bug](https://github.com/chmarti1/PYroMat/pull/37) already fixed.  igmix didn't receive much scrutiny in the last release beyond folding in the new _argparse() algorithm.  It looks like it's time to go back over some of the dustier corners.

**Comment by jranalli** [comment]
I think when you fixed it first time through you just left off the .units.

The test code I have has pretty complete coverage, so I don't think you need to overdo going back over it. If there's something busted hopefully the tests will catch it.

**Comment by chmarti1** [comment]
This is an absolutely awful (rookie) mistake.  After I made the original fix, I completely forgot to test the new Tlim() function.  This time, I did not make the same mistake.  This problem has been fixed in version 2.2.1.
