### ISSUE TITLE
[Review] LICENSE file does not contain actual license text

### ISSUE THREAD

**Issue by espottesmith** [chmarti1/PYroMat#54]
Very small issue: License.txt makes reference to the GPLv3 license but does not actually reproduce the text. For acceptance into JOSS, the contents of the license should actually be provided (see [here](https://joss.readthedocs.io/en/latest/review_criteria.html)).

**Comment by chmarti1** [comment]
Quite right.  This was the way I originally assembled the package back in 2015, and I haven't really revisited it since.  Easily fixed.
