### ISSUE TITLE
[Review] Insert citation to NumPy in Paper

### ISSUE THREAD

**Issue by fwitte** [chmarti1/PYroMat#62]
Hi @jranalli and @chmarti1,

since the package depends on NumPy, you could insert a citation here, see: https://numpy.org/citing-numpy/.

https://github.com/chmarti1/PYroMat/blob/ffe8f4508a19c182fc147d687063569e9816987f/joss2022/paper.md?plain=1#L101

**Comment by jranalli** [comment]
Added reference in recent commit https://github.com/chmarti1/PYroMat/commit/1a179875586cfd4f5150ac21c9a144337dbb1bd5
