### ISSUE TITLE
[Review] Repo/Docs are missing some guidelines for contribution

### ISSUE THREAD

**Issue by fwitte** [chmarti1/PYroMat#65]
Especially for less experienced git users and new developers, who want to contribute to your project, it would be very helpful to have short section in the GitHub repo and/or the documentation with information on

- [ ] how and where (e.g. have some module overview) to make changes in the source code and open pull requests,
- [ ] how to run the software tests (kind of related to https://github.com/chmarti1/PYroMat/issues/66) and
- [ ] code style and code documentation guidelines.

**Comment by chmarti1** [comment]
I don't object to the `extra_requires` idea.  That's a good suggestion.  I've modified the README to encourage people to contribute.  In terms of programming / style guide, the handbook is going to need to suffice for now.  Community contributions have been limited to small snippets of code so far, so it hasn't been important to develop a guide.
