### ISSUE TITLE
Problems with mp1.hsd

### ISSUE THREAD

**Issue by jranalli** [chmarti1/PYroMat#7]
These two calls produce different results for h (and s and d too).
steam.h(p=400,x=0.25)
  and
steam.hsd(p=400,x=0.25)

**Comment by chmarti1** [comment]
Yup.  It looks like HSD needs work.  If I don't get to it today, I'll do it this weekend.

-

Chris

________________________________

**Comment by jar339** [comment]
There's an easy fix actually, which is to just pass along the calls to .h(), .s() and .d(), which appear to work fine. Might not be optimally efficient, but it does at least provide accurate results.
