### ISSUE TITLE
Anaconda

### ISSUE THREAD

**Issue by beckerrh** [chmarti1/PYroMat#9]
Hello,
Thanks for this great package.
Is there an easy way to install pyromane with anaconda ?
Cheers

**Comment by beckerrh** [comment]
Thanks a lot for your fat answer.
I just got it to work by doing ‘pip install’ in the terminal in anaconda’s navigator (I found one can get this from clicking on the ‘play’-triangle in  the ‘Environments' panel of the navigator), where one can choose a ’Terminal’. Just worked so far for me.

Personally, I would anyhow not care so much, but I am using anaconda for teaching purposes, seams to be the easiest way to get basic things to run for python...

Best regards,
Roland

**Comment by chmarti1** [comment]
This question is now addressed in more detail in the [PYroMat User and Developer Handbook](http://pyromat.org/pdf/handbook.pdf).  As of the time of this post, section 2.1.2 (installation with pip) on page 20 specifically mentions Anaconda.
