### ISSUE TITLE
IgtMix length fails

### ISSUE THREAD

**Issue by chmarti1** [chmarti1/PYroMat#95]
The new `igtools.IgtMix` class has a bug in its `__len__()` method.  This affects other methods that rely on `__len__()` like the `__str__()` method.  It is unclear how this bug survived testing, since these methods passed testing.  It may have been a mistake merging branches during development.

The cause is a simple typo: `np.prod` should appear on line 988 instead of `np.product`.

**Comment by jranalli** [comment]
Fixed by commit dc85e204ddb88e38d7a7cca170f57f1350e37c8d
